// The Final Cut - curated data. Generated 2026-09-07 from a full review of all 1,408 frames.
// PICKS = Claude's proposed 70 in wedding-day order, grouped into story chapters.
// BENCH = strong alternates per chapter (runner-ups + crowd favorites not in the 70).
// Crowd wins come from the Photo Playoff sheet; note Walker cast ~40% of all votes.
window.ALBUM_DATA = {
  generated: '2026-09-07',
  chapters: [
    {
      id: 'prelude', title: 'The Morning at Park Hyatt', target: 9,
      note: 'Tokyo below, the details, the jerseys, and both of you getting ready.',
      picks: [
        ['0001', 'Opening frame. Tokyo from the room before anything has happened.'],
        ['0044', 'His and Her. The rings, the vows, the veil in one flat lay.'],
        ['0059', 'The Dodgers jerseys and the bed jump. Pure you two.'],
        ['0116', 'Takashi in the tux, first real smile of the day.'],
        ['0123', 'Alone at the window, the whole city waiting.'],
        ['0136', 'Lisa on the sill next to the dress. The calm before.'],
        ['0150', 'Earring going in, the smile already there.'],
        ['0183', 'Sisters and bridesmaid fluffing the veil against the skyline.'],
        ['0188', 'The veil from behind, Tokyo through it. The signature bride frame.'],
      ],
      bench: ['0015', '0042', '0074', '0112', '0165', '0176', '0178', '0186', '0199', '0208'],
    },
    {
      id: 'ceremony', title: 'The Ceremony', target: 11,
      note: 'Arrival, vows, rings, the kiss, the walk back.',
      picks: [
        ['0218', 'The garden ceremony from above. Sets the scene.'],
        ['0241', 'Takashi walking in with Mom and Dad.'],
        ['0287', 'Lisa on her parents arms, Dad mid-laugh.'],
        ['0289', 'Takashi seeing her come down the path.'],
        ['0327', 'Lisa looking up at him during the words.'],
        ['0352', 'The tear. Black and white.'],
        ['0369', 'Lisa cracking up during Takashi vows.'],
        ['0378', 'The ring bearer shushing the room.'],
        ['0410', 'Lisa laughing at him, framed by leaves.'],
        ['0413', 'The first kiss with the whole altar in frame.'],
        ['0423', 'Arms up. Married.'],
      ],
      bench: ['0303', '0344', '0401', '0435', '0440', '0271', '0394'],
    },
    {
      id: 'family', title: 'Petals and Family', target: 9,
      note: 'The exit, the big group, and the people who matter most.',
      picks: [
        ['0446', 'Lisa screaming with joy between Makenzie and the best man.'],
        ['0463', 'The petal walk, both of you laughing.'],
        ['0471', 'Close in the petals, the quiet second after.'],
        ['0478', 'Everyone under the gate. The full guest list.'],
        ['0507', 'With Grandpa, all three of you laughing.'],
        ['0518', 'Takashi with his parents, his head on Dad.'],
        ['0589', 'Lisa and Mom.'],
        ['0598', 'Lisa with her sisters, mid-laugh.'],
        ['0673', 'The girls twirling in the garden. The crowd favorite.'],
      ],
      bench: ['0468', '0573', '0648', '0614', '0685', '0680', '0555', '0537'],
    },
    {
      id: 'teahouse', title: 'The Teahouse', target: 9,
      note: 'Portraits in the corridors, tatami room, and garden.',
      picks: [
        ['0714', 'Lisa head back laughing in the corridor.'],
        ['0744', 'Lisa in the veil, the beauty portrait.'],
        ['0761', 'The train across the tatami, window light. Black and white.'],
        ['0763', 'Silhouette of the two of you in the shoji frame.'],
        ['0778', 'Wide teahouse and maple, the two of you tiny on the stone.'],
        ['0818', 'Under the veil, green bokeh.'],
        ['0827', 'Her hand on his back, the ring.'],
        ['0839', 'Lisa glancing back over her shoulder on the path.'],
        ['0893', 'The big laugh, walking away from the teahouse.'],
      ],
      bench: ['0699', '0715', '0735', '0784', '0816', '0863', '0871', '0892'],
    },
    {
      id: 'shrine', title: 'The Shrine', target: 9,
      note: 'The blessing, the sake, then the red torii path.',
      picks: [
        ['0929', 'The shrine hall, wide, the two of you at the far end.'],
        ['0927', 'Lisa sipping the sake.'],
        ['0946', 'Praying together at the bell.'],
        ['0964', 'The red shrine from the steps, wide.'],
        ['1003', 'Laughing down the torii path.'],
        ['1008', 'Walking away, the dress swishing.'],
        ['1024', 'The twirl in front of the torii.'],
        ['1031', 'The dip kiss.'],
        ['1088', 'Wrapped up against the red lattice wall.'],
      ],
      bench: ['0902', '0915', '0976', '1033', '1074', '1059', '0987', '1043'],
    },
    {
      id: 'shinjuku', title: 'Shinjuku', target: 7,
      note: 'The short dress, Godzilla, crosswalks, lanterns, the taxi.',
      picks: [
        ['1107', 'Godzilla over Kabukicho. The location card.'],
        ['1113', 'Long exposure kiss in the crosswalk. Black and white.'],
        ['1117', 'Laughing in the middle of the street.'],
        ['1167', 'The taxi blur past you.'],
        ['1177', 'The lift in the crosswalk.'],
        ['1187', 'Omoide Yokocho under the lanterns.'],
        ['1208', 'Backseat of the taxi, both laughing. Crowd top three.'],
      ],
      bench: ['1105', '1126', '1154', '1194', '1202', '1199', '1141'],
    },
    {
      id: 'reception', title: 'The Reception', target: 12,
      note: 'Anchor Point, the entrance, the sake barrel, speeches, cake.',
      picks: [
        ['1230', 'The room before the guests, garden through the glass.'],
        ['1252', 'The grand entrance from the balcony.'],
        ['1267', 'Kagami-biraki. The petal burst.'],
        ['1271', 'The toast over the barrel.'],
        ['1274', 'Kanpai with the tables.'],
        ['1292', 'The polaroid guestbook.'],
        ['1299', 'Cutting the cake.'],
        ['1348', 'Takashi Dad at the mic.'],
        ['1352', 'Lisa listening, hands together.'],
        ['1354', 'Lisa Dad speech. Black and white.'],
        ['1366', 'The flower girl asleep on the table.'],
        ['1372', 'Your thank-you speech.'],
      ],
      bench: ['1260', '1291', '1309', '1323', '1357', '1368', '1338', '1318', '1363'],
    },
    {
      id: 'night', title: 'Good Night, Tokyo', target: 4,
      note: 'Outside Anchor Point, string lights, heart sunglasses.',
      picks: [
        ['1379', 'Arms up outside Anchor Point.'],
        ['1382', 'Dip kiss under the Anchor Point sign.'],
        ['1391', 'Foreheads under the string lights.'],
        ['1404', 'Heart sunglasses. Closing frame.'],
      ],
      bench: ['1393', '1399', '1401', '1408', '1409', '1378'],
    },
  ],
};
